import type { Category, Product } from "./types";

export const CATEGORIES: Category[] = [
  "Embalagens",
  "Presentes",
  "Decorações",
  "Sazonais",
];

export const DEFAULT_MENU: Product[] = [
  {
    id: "1",
    name: "Caixa Kraft com Tampa",
    cat: "Embalagens",
    desc: "Caixa rígida para kits e presentes.",
    priceR: 7.9,
    priceW: 5.5,
    wholeMin: 12,
    sizes: ["P", "M", "G"],
    colors: ["Kraft", "Branco"],
    emoji: "📦",
    season: "",
  },
  {
    id: "2",
    name: "Saco Celofane Transparente",
    cat: "Embalagens",
    desc: "Pacote com 50un, para doces e lembrancinhas.",
    priceR: 14.9,
    priceW: 11.0,
    wholeMin: 6,
    sizes: ["15x30", "20x40"],
    colors: ["Liso", "Poá"],
    emoji: "🛍️",
    season: "",
  },
  {
    id: "3",
    name: "Laço de Cetim",
    cat: "Embalagens",
    desc: "Laço pronto adesivado, vários tons.",
    priceR: 3.5,
    priceW: 2.2,
    wholeMin: 20,
    sizes: [],
    colors: ["Vermelho", "Dourado", "Rosé", "Verde"],
    emoji: "🎀",
    season: "",
  },
  {
    id: "4",
    name: "Kit Presente Montado",
    cat: "Presentes",
    desc: "Caixa + papel + laço prontos para presentear.",
    priceR: 29.9,
    priceW: 24.0,
    wholeMin: 5,
    sizes: [],
    colors: ["Rosé", "Clássico"],
    emoji: "🎁",
    season: "",
  },
  {
    id: "5",
    name: "Vela Aromática Decorativa",
    cat: "Presentes",
    desc: "Vela em pote de vidro, aromas variados.",
    priceR: 24.9,
    priceW: 18.0,
    wholeMin: 6,
    sizes: [],
    colors: ["Lavanda", "Baunilha", "Capim-limão"],
    emoji: "🕯️",
    season: "",
  },
  {
    id: "6",
    name: "Guirlanda Decorativa",
    cat: "Decorações",
    desc: "Guirlanda artesanal para porta.",
    priceR: 49.9,
    priceW: 39.0,
    wholeMin: 3,
    sizes: ["30cm", "40cm"],
    colors: ["Natural", "Branca"],
    emoji: "🌿",
    season: "",
  },
  {
    id: "7",
    name: "Bola de Natal (cartela 6un)",
    cat: "Sazonais",
    desc: "Enfeites para árvore, cartela com 6.",
    priceR: 19.9,
    priceW: 14.5,
    wholeMin: 10,
    sizes: [],
    colors: ["Vermelho", "Dourado", "Prata"],
    emoji: "🎄",
    season: "Natal",
  },
  {
    id: "8",
    name: "Ovo de Páscoa para Montar",
    cat: "Sazonais",
    desc: "Forma + embalagem + laço para ovo de colher.",
    priceR: 12.9,
    priceW: 9.0,
    wholeMin: 10,
    sizes: ["250g", "500g"],
    colors: [],
    emoji: "🥚",
    season: "Páscoa",
  },
];

/** Gradiente de fundo da arte do card por categoria. */
export const CATEGORY_ART: Record<Category, string> = {
  Embalagens: "linear-gradient(150deg, #f5e3ec, #eccdd9)",
  Presentes: "linear-gradient(150deg, #fbeede, #f1d9b0)",
  Decorações: "linear-gradient(150deg, #e3efe6, #c8ddcd)",
  Sazonais: "linear-gradient(150deg, #f6e2e2, #e7c9cf)",
};
